heat_template_version: 2015-10-15

description: |
  This is a Heat template to deploy a single Linux server running Redis slave.

parameters:

  flavor:
    description: Flavor for Cloud Servers
    type: string
    default: 1GB Standard Instance
#    default: 512MB Standard Instance

  image:
    label: Server Image
    description: Operating system to use for created servers
    type: string
    default: Centos 6 (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      - Centos 6 (PVHVM)
    description: Must be a supported operating system.

  redis_version:
    description: version of redis to install
    type: string
    default: 3.0.7

  server_hostname:
    description: Hostname for the server.
    type: string
    default: redis-slave

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string

  ssh_private_key:
    description: private key to access the created servers
    type: string

  master_ip:
    description: IP address of redis master server to which we are enslaved
    type: string

  redis_password:
    description: password for redis auth
    type: string

  redis_port:
    description: port for redis servers to listen on
    type: number
    default: 6379

  sentinel_port:
    description: port for sentinels to listen on
    type: number
    default: 26379

  stack_id:
    type: string
    default: heat

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/radeasy/redis-sentinel
    #default: https://github.com/rackspace-orchestration-templates/redis-sentinel

resources:

  slave_pw:
    type: OS::Heat::RandomString
    properties:
      length: 18
      sequence: lettersdigits


  redis_slave_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: server_hostname }
      admin_pass: { get_attr: [ slave_pw, value ] }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }
      metadata:
        rax-heat: { get_param: stack_id }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        # Change sshd port and restart sshd.
        sudo sed -i 's/^#Port .*/Port 59806/g' /etc/ssh/sshd_config
        sudo echo 'Port 22' >> /etc/ssh/sshd_config
        sudo service sshd restart
        sudo service iptables stop
        # EPEL Repository.
        sudo yum install -q -y epel-release

outputs:

  redis_slave_ip:
    value: { get_attr: [redis_slave_server, accessIPv4] }

  slave_pw:
    value: { get_attr: [slave_pw, value] }