heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running elasticsearch.

parameters:

  server_flavor:
    description: Flavor for Cloud Servers
    type: string
    default: 2 GB Performance

  image_name:
    label: Server Image
    description: Operating system to use for created servers
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 13.10 (Saucy Salamander)
    description: Must be a supported operating system.

  server_hostname:
    description: Hostname for the server.
    type: string
    default: redis-slave

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string
    default: jgbes

  ssh_private_key:
    description: private key to access the created servers
    type: string

  master_ip:
    description: IP address of redis master server to which we are enslaved
    type: string

  redis_password:
    description: password for redis auth
    type: string

  redis_port:
    description: port for redis servers to listen on
    type: number
    default: 6379

  sentinel_port:
    description: port for sentinels to listen on
    type: number
    default: 26379

resources:

  redis_slave_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: server_flavor }
      image: { get_param: image_name }
      key_name: { get_param: ssh_keypair_name }

  redis_slave_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: redis_slave_server
    properties:
      username: root
      private_key: { get_param: ssh_private_key }
      host: { get_attr: [redis_slave_server, accessIPv4] }
      kitchen: https://github.com/rackspace-orchestration-templates/redis-sentinel.git
      node:
        run_list: [ "recipe[rax-redis::config_slave_sentinel]" ]
        redisio:
          default_settings:
            slaveof:
              address:  { get_param: master_ip }
              port:     { get_param: redis_port }
            masterauth: { get_param: redis_password }
          servers:
            - name: slave
              port: { get_param: redis_port }
          sentinels:
            - sentinel_port: { get_param: sentinel_port }
              port:          { get_param: sentinel_port }
              name: 'cluster'
              master_ip:     { get_param: master_ip }
              master_port:   { get_param: redis_port }
              auth-pass:     { get_param: redis_password }
              logfile: /var/log/sentinel.log

outputs:

  redis_slave_ip:
    value: { get_attr: [redis_slave_server, accessIPv4] }
